app: cdn
config:
  backends:
    example:
      origin: https://example.com
      headers:
        host: example.com
    onehostname:
      type: github_page
      origin: https://superfly.github.io
      headers:
        host: onehostname.com
  rules:
  - actionType: rewrite
    backendKey: example
    pathMatchMode: prefix
    pathPattern: "^\\/example\\/"
  - actionType: redirect
    pathMatchMode: full
    pathPattern: "^\\/example$"
    redirectURLPattern: "/example/"
  - actionType: rewrite
    backendKey: onehostname
    pathMatchMode: prefix
    pathPattern: "^\\/"
  middleware:
  - type: https-upgrader
  - type: response-headers
    headers:
      Powered-By: Caffeine