config:
  backends:
    ypk5go6e4d9em1lq:
      type: github_page
      origin: https://flyio.github.io
      headers:
        host: fly.io
    qezyml67e2rg3xn9:
      type: ''
      origin: https://arstechnica.com
      headers:
        host: "arstechnica.com"
  rules:
  - actionType: rewrite
    backendKey: qezyml67e2rg3xn9
    pathMatchMode: prefix
    pathPattern: "^\\/ars\\/"
    pathReplacementPattern: "/"
  - actionType: redirect
    backendKey: qezyml67e2rg3xn9
    pathMatchMode: full
    pathPattern: "^\\/ars$"
    redirectURLPattern: "/ars/"
  - actionType: rewrite
    backendKey: ypk5go6e4d9em1lq
    pathMatchMode: prefix
    pathPattern: "^\\/"
  middleware:
  - https-upgrader
  - - response-headers
    - header_definition:
        Powered-By: Caffeine
        X-Frame-Options: false